# Generated by Django 4.2.4 on 2023-09-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Country', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='fa_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
