# Generated by Django 4.2.4 on 2023-09-13 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Country', '0002_alter_country_fa_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
