# Generated by Django 4.2.4 on 2023-09-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_plan_remove_account_username_account_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
