# Generated by Django 4.2.4 on 2023-09-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('device', models.CharField(max_length=100)),
            ],
        ),
    ]
