# Generated by Django 4.2.2 on 2023-08-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='icon',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
