# Generated by Django 4.2.2 on 2023-08-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tag', '0002_tag_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('en_title',)},
        ),
        migrations.AddField(
            model_name='tag',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
