# Generated by Django 4.2.2 on 2023-07-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0002_person_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
