# Generated by Django 4.2.2 on 2023-07-27 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0004_alter_person_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
    ]
