# Generated by Django 4.2.2 on 2023-06-06 13:35

import Movie.models
import Utility.views
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Person', '0001_initial'),
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uuid', models.CharField(default=Utility.views.get_uuid, max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Franchise',
                'verbose_name_plural': '     Franchises',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(blank=True, max_length=100, null=True)),
                ('uuid', models.CharField(default=Utility.views.get_uuid, max_length=10, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True)),
                ('title', models.CharField(max_length=300)),
                ('poster_img', models.FileField(blank=True, null=True, upload_to=Movie.models.get_poster_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])])),
                ('item_img', models.FileField(blank=True, null=True, upload_to=Movie.models.get_item_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])])),
                ('rating', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(blank=True, max_length=300, null=True)),
                ('country', models.CharField(blank=True, max_length=300, null=True)),
                ('budget', models.CharField(blank=True, max_length=300, null=True)),
                ('certificate', models.CharField(blank=True, max_length=300, null=True)),
                ('resolution', models.CharField(blank=True, max_length=300, null=True)),
                ('duration', models.CharField(blank=True, max_length=300, null=True)),
                ('quotes', models.TextField(blank=True)),
                ('en_story', models.TextField(blank=True)),
                ('fa_story', models.TextField(blank=True)),
                ('show_poster', models.BooleanField(default=True)),
                ('ultra', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('cast', models.ManyToManyField(blank=True, related_name='movie_cast', to='Person.person')),
                ('directors', models.ManyToManyField(blank=True, related_name='movie_directors', to='Person.person')),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Movie.franchise')),
                ('genre', models.ManyToManyField(blank=True, to='Category.category')),
                ('writers', models.ManyToManyField(blank=True, related_name='movie_writers', to='Person.person')),
            ],
            options={
                'verbose_name_plural': '    Movies',
                'ordering': ('-published_at',),
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=Movie.models.get_video_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('resolution', models.CharField(blank=True, max_length=300, null=True)),
                ('duration', models.CharField(blank=True, max_length=300, null=True)),
                ('size', models.CharField(blank=True, max_length=300, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie.movie')),
            ],
            options={
                'verbose_name_plural': '   Videos',
            },
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('resolution', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to=Movie.models.get_trailer_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=Utility.views.get_uuid, max_length=10)),
                ('srt', models.FileField(upload_to=Movie.models.get_subtitle_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['srt'])])),
                ('vtt', models.FileField(blank=True, null=True, upload_to=Movie.models.get_subtitle_path_vtt, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['vtt'])])),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie.movie')),
            ],
            options={
                'verbose_name_plural': '  Subtitles',
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=Movie.models.get_audio_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'aac', 'mka'])])),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie.movie')),
            ],
            options={
                'verbose_name_plural': ' Audios',
            },
        ),
    ]
