# Generated by Django 4.2.2 on 2023-06-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, null=True,blank=True),
            preserve_default=False,
        ),
    ]
