# Generated by Django 4.2.2 on 2023-06-06 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0003_alter_franchise_published_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franchise',
            name='published_at',
        ),
    ]
