# Generated by Django 4.2.2 on 2023-06-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0005_franchise_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
