# Generated by Django 4.2.2 on 2023-06-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0007_video_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='en_story',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='fa_story',
            field=models.TextField(blank=True, null=True),
        ),
    ]
