# Generated by Django 4.2.2 on 2023-06-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0008_alter_movie_en_story_alter_movie_fa_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='qrCode',
            field=models.TextField(blank=True, null=True),
        ),
    ]
