# Generated by Django 4.2.2 on 2023-06-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0009_movie_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='colors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='freq_color',
            field=models.TextField(blank=True, null=True),
        ),
    ]
