# Generated by Django 4.2.2 on 2023-07-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0010_movie_colors_movie_freq_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='sizeb',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
