# Generated by Django 4.2.2 on 2023-07-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0011_video_sizeb'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='second_color',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='third_color',
            field=models.TextField(blank=True, null=True),
        ),
    ]
