# Generated by Django 4.2.2 on 2023-07-11 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0012_movie_second_color_movie_third_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='colors',
        ),
    ]
