# Generated by Django 4.2.2 on 2023-07-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0013_remove_movie_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
