# Generated by Django 4.2.2 on 2023-07-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0014_movie_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='corrected',
            field=models.BooleanField(default=False),
        ),
    ]
