# Generated by Django 4.2.2 on 2023-07-16 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0015_video_corrected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='corrected',
        ),
    ]
