# Generated by Django 4.2.2 on 2023-07-21 19:34

import Movie.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0016_remove_video_corrected'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='franchise',
            options={'ordering': ('-published_at',), 'verbose_name': 'Franchise', 'verbose_name_plural': '     Franchises'},
        ),
        migrations.AddField(
            model_name='movie',
            name='compress_img',
            field=models.FileField(blank=True, null=True, upload_to=Movie.models.get_compress_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])]),
        ),
    ]
