# Generated by Django 4.2.2 on 2023-07-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0017_alter_franchise_options_movie_compress_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
