# Generated by Django 4.2.2 on 2023-07-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0018_movie_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='subbed',
            field=models.BooleanField(default=False),
        ),
    ]
