# Generated by Django 4.2.2 on 2023-08-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0019_movie_subbed'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='fa_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
