# Generated by Django 4.2.2 on 2023-08-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tag', '0001_initial'),
        ('Movie', '0020_movie_fa_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='movie_tags', to='Tag.tag'),
        ),
    ]
