# Generated by Django 4.2.2 on 2023-08-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tag', '0003_alter_tag_options_tag_url'),
        ('Movie', '0022_alter_movie_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='movie_tags', to='Tag.tag'),
        ),
    ]
