# Generated by Django 4.2.2 on 2023-08-15 07:31

import Utility.views
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0023_alter_movie_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='uuid',
            field=models.CharField(default=Utility.views.get_uuid, max_length=10),
        ),
    ]
