# Generated by Django 4.2.2 on 2023-08-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0024_video_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subbed',
            field=models.BooleanField(default=False),
        ),
    ]
