# Generated by Django 4.2.2 on 2023-08-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0025_video_subbed'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='dubbed',
            field=models.BooleanField(default=False),
        ),
    ]
