# Generated by Django 4.2.4 on 2023-09-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Country', '0002_alter_country_fa_name'),
        ('Movie', '0028_movie_bac_c'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='country',
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.ManyToManyField(blank=True, to='Country.country'),
        ),
    ]
