# Generated by Django 4.2.4 on 2023-09-04 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0029_remove_movie_country_movie_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='bac_c',
        ),
    ]
