# Generated by Django 4.2.4 on 2023-09-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0030_remove_movie_bac_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='language',
            field=models.CharField(default='Persian', max_length=100),
        ),
    ]
