# Generated by Django 4.2.4 on 2023-09-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0031_subtitle_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='language',
            field=models.CharField(default='فارسی', max_length=100),
        ),
    ]
