# Generated by Django 5.0.6 on 2025-03-21 12:24

import Movie.models
import django.core.validators
import video_encoding.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0032_alter_subtitle_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=video_encoding.fields.VideoField(upload_to=Movie.models.get_video_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
