# Generated by Django 5.0.13 on 2025-03-27 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0033_alter_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie.video'),
        ),
    ]
