# Generated by Django 5.0.13 on 2025-03-27 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0034_subtitle_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitle',
            name='movie',
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie.video'),
        ),
    ]
