# Generated by Django 5.0.13 on 2025-03-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0035_remove_subtitle_movie_alter_subtitle_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='has_intro',
            field=models.BooleanField(default=False),
        ),
    ]
