# Generated by Django 5.0.13 on 2025-04-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0036_video_has_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='json_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20),
        ),
    ]
