# Generated by Django 5.0.13 on 2025-04-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0037_video_json_data_video_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='error_message',
            field=models.TextField(blank=True),
        ),
    ]
