# Generated by Django 5.2.3 on 2025-07-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0038_video_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='action',
            field=models.CharField(blank=True, choices=[('subtitle', 'Subtitle'), ('intro', 'Intro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(blank=True, choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20, null=True),
        ),
    ]
