# Generated by Django 5.2.3 on 2025-07-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0039_video_action_video_last_update_alter_video_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('nothing', 'Nothing'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='nothing', max_length=20),
        ),
    ]
