# Generated by Django 5.2.3 on 2025-07-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0040_alter_video_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
