# Generated by Django 4.2.4 on 2023-09-13 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(default='در حال انتظار', max_length=500)),
                ('done', models.BooleanField(default=False)),
                ('color', models.CharField(default='#f90', max_length=100)),
                ('priority', models.CharField(choices=[(1, 'بالا'), (2, 'معمولی'), (3, 'پایین')], default='2', max_length=200)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('blong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lists.list')),
            ],
        ),
    ]
