# Generated by Django 4.2.4 on 2023-09-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='en_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
