# Generated by Django 4.2.4 on 2023-09-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0002_list_en_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='blong',
            new_name='belong',
        ),
    ]
