# Generated by Django 4.2.4 on 2023-09-13 19:37

import Utility.views
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0003_rename_blong_item_belong'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='uuid',
            field=models.CharField(default=Utility.views.get_uuid, max_length=10, unique=True),
        ),
    ]
