# Generated by Django 4.2.4 on 2023-09-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0005_list_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='icon',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='priority',
            field=models.CharField(choices=[('1', 'بالا'), ('2', 'معمولی'), ('3', 'پایین')], default='2', max_length=200),
        ),
    ]
