# Generated by Django 4.2.4 on 2023-09-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0006_list_icon_alter_item_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='color',
            field=models.CharField(default='#ff9900', max_length=100),
        ),
        migrations.AddField(
            model_name='list',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='list',
            name='status',
            field=models.CharField(default='در حال انتظار', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(default='#ff9900', max_length=100),
        ),
    ]
