# Generated by Django 4.2.4 on 2023-09-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0007_list_color_list_done_list_status_alter_item_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, default='در حال انتظار', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='status',
            field=models.CharField(blank=True, default='در حال انتظار', max_length=500, null=True),
        ),
    ]
