# Generated by Django 4.2.4 on 2023-09-21 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0008_alter_item_status_alter_list_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ('-done',)},
        ),
    ]
