# Generated by Django 4.2.2 on 2023-06-06 13:35

import Serial.models
import Utility.views
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Person', '0001_initial'),
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=Utility.views.get_uuid, editable=False, max_length=10, unique=True)),
                ('number', models.IntegerField()),
                ('duration', models.CharField(blank=True, max_length=250, null=True)),
                ('size', models.CharField(blank=True, max_length=250, null=True)),
                ('resolution', models.CharField(blank=True, max_length=250, null=True)),
                ('video', models.FileField(upload_to=Serial.models.get_video_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='ویدیو')),
            ],
            options={
                'ordering': ('serial', 'number'),
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=Utility.views.get_uuid, editable=False, max_length=10, unique=True)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(blank=True, max_length=100, null=True)),
                ('uuid', models.CharField(default=Utility.views.get_uuid, max_length=10, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True)),
                ('title', models.CharField(max_length=300)),
                ('poster_img', models.FileField(upload_to=Serial.models.get_poster_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])])),
                ('item_img', models.FileField(upload_to=Serial.models.get_item_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])])),
                ('rating', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(blank=True, max_length=300, null=True)),
                ('country', models.CharField(blank=True, max_length=300, null=True)),
                ('budget', models.CharField(blank=True, max_length=300, null=True)),
                ('certificate', models.CharField(blank=True, max_length=300, null=True)),
                ('resolution', models.CharField(blank=True, max_length=300, null=True)),
                ('duration', models.CharField(blank=True, max_length=300, null=True)),
                ('quotes', models.TextField(blank=True)),
                ('en_story', models.TextField(blank=True)),
                ('fa_story', models.TextField(blank=True)),
                ('show_poster', models.BooleanField(default=True)),
                ('ultra', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('cast', models.ManyToManyField(blank=True, related_name='serial_cast', to='Person.person')),
                ('directors', models.ManyToManyField(blank=True, related_name='serial_directors', to='Person.person')),
                ('genre', models.ManyToManyField(blank=True, to='Category.category')),
                ('writers', models.ManyToManyField(blank=True, related_name='serial_writers', to='Person.person')),
            ],
            options={
                'ordering': ('-published_at',),
            },
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('resolution', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to=Serial.models.get_trailer_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Serial.serial')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonSubtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.FileField(blank=True, null=True, upload_to=Serial.models.get_subtitle_path_season, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['rar', 'zip'])])),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Serial.season')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Serial.serial'),
        ),
        migrations.CreateModel(
            name='EpisodeSubtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srt', models.FileField(upload_to=Serial.models.get_subtitle_path_episode, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['srt'])])),
                ('vtt', models.FileField(blank=True, null=True, upload_to=Serial.models.get_subtitle_path_episode_vtt, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['srt'])])),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Serial.episode')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Serial.season', verbose_name='فصل'),
        ),
        migrations.AddField(
            model_name='episode',
            name='serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Serial.serial', verbose_name='سریال'),
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=Serial.models.get_audio_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'aac'])])),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Serial.episode')),
            ],
        ),
    ]
