# Generated by Django 4.2.2 on 2023-06-16 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Serial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={},
        ),
        migrations.AddField(
            model_name='episode',
            name='corrected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='episode',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
