# Generated by Django 4.2.2 on 2023-06-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serial', '0002_alter_episode_options_episode_corrected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='qrCode',
            field=models.TextField(blank=True, null=True),
        ),
    ]
