# Generated by Django 4.2.2 on 2023-07-15 22:13

import Serial.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serial', '0003_serial_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='item_img',
            field=models.FileField(blank=True, null=True, upload_to=Serial.models.get_item_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='serial',
            name='poster_img',
            field=models.FileField(blank=True, null=True, upload_to=Serial.models.get_poster_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])]),
        ),
    ]
