# Generated by Django 4.2.2 on 2023-07-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serial', '0004_alter_serial_item_img_alter_serial_poster_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='freq_color',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serial',
            name='second_color',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serial',
            name='third_color',
            field=models.TextField(blank=True, null=True),
        ),
    ]
