# Generated by Django 4.2.2 on 2023-07-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serial', '0005_serial_freq_color_serial_second_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ('serial', 'number')},
        ),
        migrations.AddField(
            model_name='serial',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
