# Generated by Django 4.2.2 on 2023-07-21 19:35

import Serial.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serial', '0006_alter_episode_options_serial_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='compress_img',
            field=models.FileField(blank=True, null=True, upload_to=Serial.models.get_compress_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])]),
        ),
    ]
