# Generated by Django 4.2.2 on 2023-07-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serial', '0007_serial_compress_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='sizeb',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
