# Generated by Django 4.2.2 on 2023-07-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serial', '0008_episode_sizeb'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
