# Generated by Django 4.2.2 on 2023-08-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tag', '0001_initial'),
        ('Serial', '0009_serial_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='serial_tags', to='Tag.tag'),
        ),
    ]
