# Generated by Django 4.2.2 on 2023-08-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tag', '0003_alter_tag_options_tag_url'),
        ('Serial', '0010_serial_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='fa_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='tags',
            field=models.ManyToManyField(related_name='serial_tags', to='Tag.tag'),
        ),
    ]
