# Generated by Django 4.2.2 on 2023-08-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serial', '0012_alter_serial_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='corrected',
        ),
        migrations.AddField(
            model_name='episode',
            name='subbed',
            field=models.BooleanField(default=False),
        ),
    ]
