# Generated by Django 4.2.2 on 2023-08-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serial', '0013_remove_episode_corrected_episode_subbed'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='dubbed',
            field=models.BooleanField(default=False),
        ),
    ]
