# Generated by Django 4.2.4 on 2023-08-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serial', '0014_episode_dubbed'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='censors',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='credits',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
