# Generated by Django 4.2.4 on 2023-09-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serial', '0015_episode_censors_episode_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='bac_c',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
