# Generated by Django 4.2.4 on 2023-09-04 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Serial', '0017_remove_serial_country_serial_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serial',
            name='bac_c',
        ),
    ]
