# Generated by Django 4.2.4 on 2023-09-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Serial', '0018_remove_serial_bac_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodesubtitle',
            name='language',
            field=models.CharField(default='Persian', max_length=100),
        ),
    ]
